// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package javapayload.loader.rmi;

public final class PollingSenderImpl_Stub
    extends java.rmi.server.RemoteStub
    implements javapayload.loader.rmi.PollingSender
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_sendData_0;
    
    static {
	try {
	    $method_sendData_0 = javapayload.loader.rmi.PollingSender.class.getMethod("sendData", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public PollingSenderImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of sendData(String)
    public java.lang.String sendData(java.lang.String $param_String_1)
	throws java.io.IOException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_sendData_0, new java.lang.Object[] {$param_String_1}, 3978353600975005701L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.io.IOException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
